services:
  txbuilder-ethereum:
    container_name: txbuilder-ethereum
    build:
      context: .
      dockerfile: Dockerfile
    image: txbuilder-ethereum:latest
    ports:
      - "51051:51051"
    volumes:
      - ./config/config.docker.toml:/app/config/config.docker.toml:ro
    restart: unless-stopped
    networks:
      - koku-net

networks:
  koku-net:
    external: true   # 加入外部网络 koku-net
