// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: grpc/txbuilder.proto

package txbuilder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common request with trace ID
type RequestWithTraceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithTraceId) Reset() {
	*x = RequestWithTraceId{}
	mi := &file_grpc_txbuilder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithTraceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithTraceId) ProtoMessage() {}

func (x *RequestWithTraceId) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithTraceId.ProtoReflect.Descriptor instead.
func (*RequestWithTraceId) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithTraceId) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// VerifyAddress
type VerifyAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressRequest) Reset() {
	*x = VerifyAddressRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressRequest) ProtoMessage() {}

func (x *VerifyAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressResponse) Reset() {
	*x = VerifyAddressResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressResponse) ProtoMessage() {}

func (x *VerifyAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// VerifyContractAddress
type VerifyContractAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressRequest) Reset() {
	*x = VerifyContractAddressRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressRequest) ProtoMessage() {}

func (x *VerifyContractAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyContractAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyContractAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyContractAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressResponse) Reset() {
	*x = VerifyContractAddressResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressResponse) ProtoMessage() {}

func (x *VerifyContractAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyContractAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// ConvertAddress
type ConvertAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 1-36 必填
	Keys          []*PublicKeysRequest   `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertAddressRequest) Reset() {
	*x = ConvertAddressRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAddressRequest) ProtoMessage() {}

func (x *ConvertAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAddressRequest.ProtoReflect.Descriptor instead.
func (*ConvertAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ConvertAddressRequest) GetKeys() []*PublicKeysRequest {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	PkixPubkeyPem string                 `protobuf:"bytes,2,opt,name=pkix_pubkey_pem,json=pkixPubkeyPem,proto3" json:"pkix_pubkey_pem,omitempty"` // 必填；PKIX 标准的公钥，PEM 格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeysRequest) Reset() {
	*x = PublicKeysRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeysRequest) ProtoMessage() {}

func (x *PublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeysRequest.ProtoReflect.Descriptor instead.
func (*PublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{6}
}

func (x *PublicKeysRequest) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *PublicKeysRequest) GetPkixPubkeyPem() string {
	if x != nil {
		return x.PkixPubkeyPem
	}
	return ""
}

type ConvertAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*PublicKeysResponse  `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertAddressResponse) Reset() {
	*x = ConvertAddressResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAddressResponse) ProtoMessage() {}

func (x *ConvertAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAddressResponse.ProtoReflect.Descriptor instead.
func (*ConvertAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertAddressResponse) GetKeys() []*PublicKeysResponse {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublicKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // Ethereum 地址（0x + 40 hex，包含 EIP-55 校验位）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeysResponse) Reset() {
	*x = PublicKeysResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeysResponse) ProtoMessage() {}

func (x *PublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeysResponse.ProtoReflect.Descriptor instead.
func (*PublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{8}
}

func (x *PublicKeysResponse) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *PublicKeysResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// CheckSufficientBalance
type CheckSufficientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`             // 1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`       // 1-36 必填； 唯一， 表示区块链名称，如：bitcoin、ethereum、tron
	Coin          string                 `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 必填； 唯一， 表示转账币种，如：btc、eth、usdt、dog；不涉及判断逻辑，仅作展示
	FromAddress   string                 `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // 1-256 必填；转账发起地址
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                              // 必填； 金额，单位是最小该链单位，如：以太坊单位就是wei；波场单位就是sun
	Contract      string                 `protobuf:"bytes,6,opt,name=contract,proto3" json:"contract,omitempty"`                          // 1-256 非必填；转账币种对应的合约地址。如果空串表示主链币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSufficientBalanceRequest) Reset() {
	*x = CheckSufficientBalanceRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceRequest) ProtoMessage() {}

func (x *CheckSufficientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{9}
}

func (x *CheckSufficientBalanceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type CheckSufficientBalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsCoinSufficient  bool                   `protobuf:"varint,1,opt,name=is_coin_sufficient,json=isCoinSufficient,proto3" json:"is_coin_sufficient,omitempty"`    // 主链币是否足够
	IsTokenSufficient bool                   `protobuf:"varint,2,opt,name=is_token_sufficient,json=isTokenSufficient,proto3" json:"is_token_sufficient,omitempty"` // 合约余额是否足够；注意当检查合约余额时两个返回值都需要判断
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckSufficientBalanceResponse) Reset() {
	*x = CheckSufficientBalanceResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceResponse) ProtoMessage() {}

func (x *CheckSufficientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{10}
}

func (x *CheckSufficientBalanceResponse) GetIsCoinSufficient() bool {
	if x != nil {
		return x.IsCoinSufficient
	}
	return false
}

func (x *CheckSufficientBalanceResponse) GetIsTokenSufficient() bool {
	if x != nil {
		return x.IsTokenSufficient
	}
	return false
}

// BuildSignRawData
type BuildSignRawDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`             // 1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`       // 1-36 必填； 唯一， 表示区块链名称，如：bitcoin、ethereum、tron
	Coin          string                 `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 必填； 唯一， 表示转账币种，如：btc、eth、usdt、dog；不涉及判断逻辑，仅作展示
	CoinSymbol    string                 `protobuf:"bytes,4,opt,name=coin_symbol,json=coinSymbol,proto3" json:"coin_symbol,omitempty"`    // 1-36 必填； 币种符合，用于展示，不涉及逻辑
	FromAddress   string                 `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // 1-256 必填；转账发起地址
	ToAddress     string                 `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // 1-256 必填；转账接收地址
	Amount        string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`                              // 必填； 转账金额，单位是最小该链单位，如：以太坊单位就是wei；波场单位就是sun
	Contract      string                 `protobuf:"bytes,8,opt,name=contract,proto3" json:"contract,omitempty"`                          // 1-256 非必填；转账币种对应的合约地址。如果空串表示主链币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSignRawDataRequest) Reset() {
	*x = BuildSignRawDataRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSignRawDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSignRawDataRequest) ProtoMessage() {}

func (x *BuildSignRawDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSignRawDataRequest.ProtoReflect.Descriptor instead.
func (*BuildSignRawDataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{11}
}

func (x *BuildSignRawDataRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type BuildSignRawDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`                        // SHA256(raw_data) - 待签名内容
	RawData       string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // 原始交易数据 (hex 编码) - Coordinator 用于构造完整交易
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSignRawDataResponse) Reset() {
	*x = BuildSignRawDataResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSignRawDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSignRawDataResponse) ProtoMessage() {}

func (x *BuildSignRawDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSignRawDataResponse.ProtoReflect.Descriptor instead.
func (*BuildSignRawDataResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{12}
}

func (x *BuildSignRawDataResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BuildSignRawDataResponse) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

// TxBroadcast
type TxBroadcastRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TraceId string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RawData string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // 原始交易数据 (hex 编码)
	// 长度 65 个字节
	// 外部传入的签名数据，格式为 R（32字节） + S （32字节）+ V (V 1个字节，只有 0 或 1，表示 R.y 坐标的奇偶性)
	Signature     string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBroadcastRequest) Reset() {
	*x = TxBroadcastRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBroadcastRequest) ProtoMessage() {}

func (x *TxBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBroadcastRequest.ProtoReflect.Descriptor instead.
func (*TxBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{13}
}

func (x *TxBroadcastRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TxBroadcastRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *TxBroadcastRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type TxBroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"` // 交易哈希，广播成功后返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBroadcastResponse) Reset() {
	*x = TxBroadcastResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBroadcastResponse) ProtoMessage() {}

func (x *TxBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBroadcastResponse.ProtoReflect.Descriptor instead.
func (*TxBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{14}
}

func (x *TxBroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TxBroadcastResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_grpc_txbuilder_proto protoreflect.FileDescriptor

const file_grpc_txbuilder_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/txbuilder.proto\x12\ttxbuilder\"/\n" +
	"\x12RequestWithTraceId\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"K\n" +
	"\x14VerifyAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"2\n" +
	"\x15VerifyAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"S\n" +
	"\x1cVerifyContractAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\":\n" +
	"\x1dVerifyContractAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"d\n" +
	"\x15ConvertAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x04keys\x18\x02 \x03(\v2\x1c.txbuilder.PublicKeysRequestR\x04keys\"`\n" +
	"\x11PublicKeysRequest\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12&\n" +
	"\x0fpkix_pubkey_pem\x18\x02 \x01(\tR\rpkixPubkeyPem\"K\n" +
	"\x16ConvertAddressResponse\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.txbuilder.PublicKeysResponseR\x04keys\"S\n" +
	"\x12PublicKeysResponse\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xc4\x01\n" +
	"\x1dCheckSufficientBalanceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\tR\x04coin\x12!\n" +
	"\ffrom_address\x18\x04 \x01(\tR\vfromAddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\x06 \x01(\tR\bcontract\"~\n" +
	"\x1eCheckSufficientBalanceResponse\x12,\n" +
	"\x12is_coin_sufficient\x18\x01 \x01(\bR\x10isCoinSufficient\x12.\n" +
	"\x13is_token_sufficient\x18\x02 \x01(\bR\x11isTokenSufficient\"\xfe\x01\n" +
	"\x17BuildSignRawDataRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\tR\x04coin\x12\x1f\n" +
	"\vcoin_symbol\x18\x04 \x01(\tR\n" +
	"coinSymbol\x12!\n" +
	"\ffrom_address\x18\x05 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x06 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\b \x01(\tR\bcontract\"G\n" +
	"\x18BuildSignRawDataResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\"h\n" +
	"\x12TxBroadcastRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"H\n" +
	"\x13TxBroadcastResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash2\xbc\x04\n" +
	"\tTxBuilder\x12U\n" +
	"\x0eConvertAddress\x12 .txbuilder.ConvertAddressRequest\x1a!.txbuilder.ConvertAddressResponse\x12R\n" +
	"\rVerifyAddress\x12\x1f.txbuilder.VerifyAddressRequest\x1a .txbuilder.VerifyAddressResponse\x12j\n" +
	"\x15VerifyContractAddress\x12'.txbuilder.VerifyContractAddressRequest\x1a(.txbuilder.VerifyContractAddressResponse\x12m\n" +
	"\x16CheckSufficientBalance\x12(.txbuilder.CheckSufficientBalanceRequest\x1a).txbuilder.CheckSufficientBalanceResponse\x12[\n" +
	"\x10BuildSignRawData\x12\".txbuilder.BuildSignRawDataRequest\x1a#.txbuilder.BuildSignRawDataResponse\x12L\n" +
	"\vTxBroadcast\x12\x1d.txbuilder.TxBroadcastRequest\x1a\x1e.txbuilder.TxBroadcastResponseB<Z:github.com/koku-web3/go-koku/pkg/proto/txbuilder;txbuilderb\x06proto3"

var (
	file_grpc_txbuilder_proto_rawDescOnce sync.Once
	file_grpc_txbuilder_proto_rawDescData []byte
)

func file_grpc_txbuilder_proto_rawDescGZIP() []byte {
	file_grpc_txbuilder_proto_rawDescOnce.Do(func() {
		file_grpc_txbuilder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_txbuilder_proto_rawDesc), len(file_grpc_txbuilder_proto_rawDesc)))
	})
	return file_grpc_txbuilder_proto_rawDescData
}

var file_grpc_txbuilder_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_grpc_txbuilder_proto_goTypes = []any{
	(*RequestWithTraceId)(nil),             // 0: txbuilder.RequestWithTraceId
	(*VerifyAddressRequest)(nil),           // 1: txbuilder.VerifyAddressRequest
	(*VerifyAddressResponse)(nil),          // 2: txbuilder.VerifyAddressResponse
	(*VerifyContractAddressRequest)(nil),   // 3: txbuilder.VerifyContractAddressRequest
	(*VerifyContractAddressResponse)(nil),  // 4: txbuilder.VerifyContractAddressResponse
	(*ConvertAddressRequest)(nil),          // 5: txbuilder.ConvertAddressRequest
	(*PublicKeysRequest)(nil),              // 6: txbuilder.PublicKeysRequest
	(*ConvertAddressResponse)(nil),         // 7: txbuilder.ConvertAddressResponse
	(*PublicKeysResponse)(nil),             // 8: txbuilder.PublicKeysResponse
	(*CheckSufficientBalanceRequest)(nil),  // 9: txbuilder.CheckSufficientBalanceRequest
	(*CheckSufficientBalanceResponse)(nil), // 10: txbuilder.CheckSufficientBalanceResponse
	(*BuildSignRawDataRequest)(nil),        // 11: txbuilder.BuildSignRawDataRequest
	(*BuildSignRawDataResponse)(nil),       // 12: txbuilder.BuildSignRawDataResponse
	(*TxBroadcastRequest)(nil),             // 13: txbuilder.TxBroadcastRequest
	(*TxBroadcastResponse)(nil),            // 14: txbuilder.TxBroadcastResponse
}
var file_grpc_txbuilder_proto_depIdxs = []int32{
	6,  // 0: txbuilder.ConvertAddressRequest.keys:type_name -> txbuilder.PublicKeysRequest
	8,  // 1: txbuilder.ConvertAddressResponse.keys:type_name -> txbuilder.PublicKeysResponse
	5,  // 2: txbuilder.TxBuilder.ConvertAddress:input_type -> txbuilder.ConvertAddressRequest
	1,  // 3: txbuilder.TxBuilder.VerifyAddress:input_type -> txbuilder.VerifyAddressRequest
	3,  // 4: txbuilder.TxBuilder.VerifyContractAddress:input_type -> txbuilder.VerifyContractAddressRequest
	9,  // 5: txbuilder.TxBuilder.CheckSufficientBalance:input_type -> txbuilder.CheckSufficientBalanceRequest
	11, // 6: txbuilder.TxBuilder.BuildSignRawData:input_type -> txbuilder.BuildSignRawDataRequest
	13, // 7: txbuilder.TxBuilder.TxBroadcast:input_type -> txbuilder.TxBroadcastRequest
	7,  // 8: txbuilder.TxBuilder.ConvertAddress:output_type -> txbuilder.ConvertAddressResponse
	2,  // 9: txbuilder.TxBuilder.VerifyAddress:output_type -> txbuilder.VerifyAddressResponse
	4,  // 10: txbuilder.TxBuilder.VerifyContractAddress:output_type -> txbuilder.VerifyContractAddressResponse
	10, // 11: txbuilder.TxBuilder.CheckSufficientBalance:output_type -> txbuilder.CheckSufficientBalanceResponse
	12, // 12: txbuilder.TxBuilder.BuildSignRawData:output_type -> txbuilder.BuildSignRawDataResponse
	14, // 13: txbuilder.TxBuilder.TxBroadcast:output_type -> txbuilder.TxBroadcastResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_txbuilder_proto_init() }
func file_grpc_txbuilder_proto_init() {
	if File_grpc_txbuilder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_txbuilder_proto_rawDesc), len(file_grpc_txbuilder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_txbuilder_proto_goTypes,
		DependencyIndexes: file_grpc_txbuilder_proto_depIdxs,
		MessageInfos:      file_grpc_txbuilder_proto_msgTypes,
	}.Build()
	File_grpc_txbuilder_proto = out.File
	file_grpc_txbuilder_proto_goTypes = nil
	file_grpc_txbuilder_proto_depIdxs = nil
}
