// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: grpc/txbuilder.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common request with trace ID
type RequestWithTraceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithTraceId) Reset() {
	*x = RequestWithTraceId{}
	mi := &file_grpc_txbuilder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithTraceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithTraceId) ProtoMessage() {}

func (x *RequestWithTraceId) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithTraceId.ProtoReflect.Descriptor instead.
func (*RequestWithTraceId) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithTraceId) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// VerifyAddress
type VerifyAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressRequest) Reset() {
	*x = VerifyAddressRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressRequest) ProtoMessage() {}

func (x *VerifyAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressResponse) Reset() {
	*x = VerifyAddressResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressResponse) ProtoMessage() {}

func (x *VerifyAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// VerifyContractAddress
type VerifyContractAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressRequest) Reset() {
	*x = VerifyContractAddressRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressRequest) ProtoMessage() {}

func (x *VerifyContractAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyContractAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyContractAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyContractAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressResponse) Reset() {
	*x = VerifyContractAddressResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressResponse) ProtoMessage() {}

func (x *VerifyContractAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyContractAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// CheckSufficientBalance
type CheckSufficientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	CoinId        string                 `protobuf:"bytes,3,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	IsBasicCoin   bool                   `protobuf:"varint,4,opt,name=is_basic_coin,json=isBasicCoin,proto3" json:"is_basic_coin,omitempty"`
	FromAddress   string                 `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Contract      string                 `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSufficientBalanceRequest) Reset() {
	*x = CheckSufficientBalanceRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceRequest) ProtoMessage() {}

func (x *CheckSufficientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSufficientBalanceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetCoinId() string {
	if x != nil {
		return x.CoinId
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetIsBasicCoin() bool {
	if x != nil {
		return x.IsBasicCoin
	}
	return false
}

func (x *CheckSufficientBalanceRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type CheckSufficientBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSufficient  bool                   `protobuf:"varint,1,opt,name=is_sufficient,json=isSufficient,proto3" json:"is_sufficient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSufficientBalanceResponse) Reset() {
	*x = CheckSufficientBalanceResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceResponse) ProtoMessage() {}

func (x *CheckSufficientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{6}
}

func (x *CheckSufficientBalanceResponse) GetIsSufficient() bool {
	if x != nil {
		return x.IsSufficient
	}
	return false
}

// BuildSignRawData
type BuildSignRawDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	CoinId        string                 `protobuf:"bytes,3,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	IsBasicCoin   bool                   `protobuf:"varint,4,opt,name=is_basic_coin,json=isBasicCoin,proto3" json:"is_basic_coin,omitempty"`
	CoinSymbol    string                 `protobuf:"bytes,5,opt,name=coin_symbol,json=coinSymbol,proto3" json:"coin_symbol,omitempty"`
	FromAddress   string                 `protobuf:"bytes,6,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,7,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        string                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Contract      string                 `protobuf:"bytes,9,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSignRawDataRequest) Reset() {
	*x = BuildSignRawDataRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSignRawDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSignRawDataRequest) ProtoMessage() {}

func (x *BuildSignRawDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSignRawDataRequest.ProtoReflect.Descriptor instead.
func (*BuildSignRawDataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{7}
}

func (x *BuildSignRawDataRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetCoinId() string {
	if x != nil {
		return x.CoinId
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetIsBasicCoin() bool {
	if x != nil {
		return x.IsBasicCoin
	}
	return false
}

func (x *BuildSignRawDataRequest) GetCoinSymbol() string {
	if x != nil {
		return x.CoinSymbol
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BuildSignRawDataRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type BuildSignRawDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`                        // Keccak-256 hash of unsigned tx - message to sign
	RawData       string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // Unsigned RLP encoded transaction (hex) - for Coordinator to sign
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSignRawDataResponse) Reset() {
	*x = BuildSignRawDataResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSignRawDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSignRawDataResponse) ProtoMessage() {}

func (x *BuildSignRawDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSignRawDataResponse.ProtoReflect.Descriptor instead.
func (*BuildSignRawDataResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{8}
}

func (x *BuildSignRawDataResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BuildSignRawDataResponse) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

// TxBroadcast
type TxBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RawData       string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // Signed RLP encoded transaction (hex)
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`            // Signature (hex) - kept for compatibility, ignored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBroadcastRequest) Reset() {
	*x = TxBroadcastRequest{}
	mi := &file_grpc_txbuilder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBroadcastRequest) ProtoMessage() {}

func (x *TxBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBroadcastRequest.ProtoReflect.Descriptor instead.
func (*TxBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{9}
}

func (x *TxBroadcastRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TxBroadcastRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *TxBroadcastRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type TxBroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBroadcastResponse) Reset() {
	*x = TxBroadcastResponse{}
	mi := &file_grpc_txbuilder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBroadcastResponse) ProtoMessage() {}

func (x *TxBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_txbuilder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBroadcastResponse.ProtoReflect.Descriptor instead.
func (*TxBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_grpc_txbuilder_proto_rawDescGZIP(), []int{10}
}

func (x *TxBroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grpc_txbuilder_proto protoreflect.FileDescriptor

const file_grpc_txbuilder_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/txbuilder.proto\x12\x05chain\"/\n" +
	"\x12RequestWithTraceId\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"K\n" +
	"\x14VerifyAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"2\n" +
	"\x15VerifyAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"S\n" +
	"\x1cVerifyContractAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\":\n" +
	"\x1dVerifyContractAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"\xed\x01\n" +
	"\x1dCheckSufficientBalanceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x17\n" +
	"\acoin_id\x18\x03 \x01(\tR\x06coinId\x12\"\n" +
	"\ris_basic_coin\x18\x04 \x01(\bR\visBasicCoin\x12!\n" +
	"\ffrom_address\x18\x05 \x01(\tR\vfromAddress\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\a \x01(\tR\bcontract\"E\n" +
	"\x1eCheckSufficientBalanceResponse\x12#\n" +
	"\ris_sufficient\x18\x01 \x01(\bR\fisSufficient\"\xa3\x02\n" +
	"\x17BuildSignRawDataRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x17\n" +
	"\acoin_id\x18\x03 \x01(\tR\x06coinId\x12\"\n" +
	"\ris_basic_coin\x18\x04 \x01(\bR\visBasicCoin\x12\x1f\n" +
	"\vcoin_symbol\x18\x05 \x01(\tR\n" +
	"coinSymbol\x12!\n" +
	"\ffrom_address\x18\x06 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\a \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\b \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\t \x01(\tR\bcontract\"G\n" +
	"\x18BuildSignRawDataResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\"h\n" +
	"\x12TxBroadcastRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"/\n" +
	"\x13TxBroadcastResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbd\x03\n" +
	"\tTxBuilder\x12J\n" +
	"\rVerifyAddress\x12\x1b.chain.VerifyAddressRequest\x1a\x1c.chain.VerifyAddressResponse\x12b\n" +
	"\x15VerifyContractAddress\x12#.chain.VerifyContractAddressRequest\x1a$.chain.VerifyContractAddressResponse\x12e\n" +
	"\x16CheckSufficientBalance\x12$.chain.CheckSufficientBalanceRequest\x1a%.chain.CheckSufficientBalanceResponse\x12S\n" +
	"\x10BuildSignRawData\x12\x1e.chain.BuildSignRawDataRequest\x1a\x1f.chain.BuildSignRawDataResponse\x12D\n" +
	"\vTxBroadcast\x12\x19.chain.TxBroadcastRequest\x1a\x1a.chain.TxBroadcastResponseB3Z1github.com/koku-web3/txbuilder-ethereum/grpc;grpcb\x06proto3"

var (
	file_grpc_txbuilder_proto_rawDescOnce sync.Once
	file_grpc_txbuilder_proto_rawDescData []byte
)

func file_grpc_txbuilder_proto_rawDescGZIP() []byte {
	file_grpc_txbuilder_proto_rawDescOnce.Do(func() {
		file_grpc_txbuilder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_txbuilder_proto_rawDesc), len(file_grpc_txbuilder_proto_rawDesc)))
	})
	return file_grpc_txbuilder_proto_rawDescData
}

var file_grpc_txbuilder_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_txbuilder_proto_goTypes = []any{
	(*RequestWithTraceId)(nil),             // 0: chain.RequestWithTraceId
	(*VerifyAddressRequest)(nil),           // 1: chain.VerifyAddressRequest
	(*VerifyAddressResponse)(nil),          // 2: chain.VerifyAddressResponse
	(*VerifyContractAddressRequest)(nil),   // 3: chain.VerifyContractAddressRequest
	(*VerifyContractAddressResponse)(nil),  // 4: chain.VerifyContractAddressResponse
	(*CheckSufficientBalanceRequest)(nil),  // 5: chain.CheckSufficientBalanceRequest
	(*CheckSufficientBalanceResponse)(nil), // 6: chain.CheckSufficientBalanceResponse
	(*BuildSignRawDataRequest)(nil),        // 7: chain.BuildSignRawDataRequest
	(*BuildSignRawDataResponse)(nil),       // 8: chain.BuildSignRawDataResponse
	(*TxBroadcastRequest)(nil),             // 9: chain.TxBroadcastRequest
	(*TxBroadcastResponse)(nil),            // 10: chain.TxBroadcastResponse
}
var file_grpc_txbuilder_proto_depIdxs = []int32{
	1,  // 0: chain.TxBuilder.VerifyAddress:input_type -> chain.VerifyAddressRequest
	3,  // 1: chain.TxBuilder.VerifyContractAddress:input_type -> chain.VerifyContractAddressRequest
	5,  // 2: chain.TxBuilder.CheckSufficientBalance:input_type -> chain.CheckSufficientBalanceRequest
	7,  // 3: chain.TxBuilder.BuildSignRawData:input_type -> chain.BuildSignRawDataRequest
	9,  // 4: chain.TxBuilder.TxBroadcast:input_type -> chain.TxBroadcastRequest
	2,  // 5: chain.TxBuilder.VerifyAddress:output_type -> chain.VerifyAddressResponse
	4,  // 6: chain.TxBuilder.VerifyContractAddress:output_type -> chain.VerifyContractAddressResponse
	6,  // 7: chain.TxBuilder.CheckSufficientBalance:output_type -> chain.CheckSufficientBalanceResponse
	8,  // 8: chain.TxBuilder.BuildSignRawData:output_type -> chain.BuildSignRawDataResponse
	10, // 9: chain.TxBuilder.TxBroadcast:output_type -> chain.TxBroadcastResponse
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_txbuilder_proto_init() }
func file_grpc_txbuilder_proto_init() {
	if File_grpc_txbuilder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_txbuilder_proto_rawDesc), len(file_grpc_txbuilder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_txbuilder_proto_goTypes,
		DependencyIndexes: file_grpc_txbuilder_proto_depIdxs,
		MessageInfos:      file_grpc_txbuilder_proto_msgTypes,
	}.Build()
	File_grpc_txbuilder_proto = out.File
	file_grpc_txbuilder_proto_goTypes = nil
	file_grpc_txbuilder_proto_depIdxs = nil
}
