// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: grpc/txbuilder.proto

package txbuilder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TxBuilder_ConvertAddress_FullMethodName         = "/txbuilder.TxBuilder/ConvertAddress"
	TxBuilder_VerifyAddress_FullMethodName          = "/txbuilder.TxBuilder/VerifyAddress"
	TxBuilder_VerifyContractAddress_FullMethodName  = "/txbuilder.TxBuilder/VerifyContractAddress"
	TxBuilder_CheckSufficientBalance_FullMethodName = "/txbuilder.TxBuilder/CheckSufficientBalance"
	TxBuilder_BuildSignRawData_FullMethodName       = "/txbuilder.TxBuilder/BuildSignRawData"
	TxBuilder_TxBroadcast_FullMethodName            = "/txbuilder.TxBuilder/TxBroadcast"
	TxBuilder_GetBalance_FullMethodName             = "/txbuilder.TxBuilder/GetBalance"
)

// TxBuilderClient is the client API for TxBuilder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TxBuilder 服务提供交易构建相关的 API
type TxBuilderClient interface {
	// 将 PEM 编码的公钥转换为以太坊地址
	ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error)
	// 验证一个地址是否有效
	VerifyAddress(ctx context.Context, in *VerifyAddressRequest, opts ...grpc.CallOption) (*VerifyAddressResponse, error)
	// 验证一个合约地址是否有效
	VerifyContractAddress(ctx context.Context, in *VerifyContractAddressRequest, opts ...grpc.CallOption) (*VerifyContractAddressResponse, error)
	// 检查余额是否足够进行转账
	CheckSufficientBalance(ctx context.Context, in *CheckSufficientBalanceRequest, opts ...grpc.CallOption) (*CheckSufficientBalanceResponse, error)
	// 构建用于签名的未签名交易原始数据
	BuildSignRawData(ctx context.Context, in *BuildSignRawDataRequest, opts ...grpc.CallOption) (*BuildSignRawDataResponse, error)
	// 广播已签名交易到网络
	TxBroadcast(ctx context.Context, in *TxBroadcastRequest, opts ...grpc.CallOption) (*TxBroadcastResponse, error)
	// 查询余额
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type txBuilderClient struct {
	cc grpc.ClientConnInterface
}

func NewTxBuilderClient(cc grpc.ClientConnInterface) TxBuilderClient {
	return &txBuilderClient{cc}
}

func (c *txBuilderClient) ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertAddressResponse)
	err := c.cc.Invoke(ctx, TxBuilder_ConvertAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) VerifyAddress(ctx context.Context, in *VerifyAddressRequest, opts ...grpc.CallOption) (*VerifyAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAddressResponse)
	err := c.cc.Invoke(ctx, TxBuilder_VerifyAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) VerifyContractAddress(ctx context.Context, in *VerifyContractAddressRequest, opts ...grpc.CallOption) (*VerifyContractAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyContractAddressResponse)
	err := c.cc.Invoke(ctx, TxBuilder_VerifyContractAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) CheckSufficientBalance(ctx context.Context, in *CheckSufficientBalanceRequest, opts ...grpc.CallOption) (*CheckSufficientBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSufficientBalanceResponse)
	err := c.cc.Invoke(ctx, TxBuilder_CheckSufficientBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) BuildSignRawData(ctx context.Context, in *BuildSignRawDataRequest, opts ...grpc.CallOption) (*BuildSignRawDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildSignRawDataResponse)
	err := c.cc.Invoke(ctx, TxBuilder_BuildSignRawData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) TxBroadcast(ctx context.Context, in *TxBroadcastRequest, opts ...grpc.CallOption) (*TxBroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxBroadcastResponse)
	err := c.cc.Invoke(ctx, TxBuilder_TxBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txBuilderClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, TxBuilder_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxBuilderServer is the server API for TxBuilder service.
// All implementations must embed UnimplementedTxBuilderServer
// for forward compatibility.
//
// TxBuilder 服务提供交易构建相关的 API
type TxBuilderServer interface {
	// 将 PEM 编码的公钥转换为以太坊地址
	ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error)
	// 验证一个地址是否有效
	VerifyAddress(context.Context, *VerifyAddressRequest) (*VerifyAddressResponse, error)
	// 验证一个合约地址是否有效
	VerifyContractAddress(context.Context, *VerifyContractAddressRequest) (*VerifyContractAddressResponse, error)
	// 检查余额是否足够进行转账
	CheckSufficientBalance(context.Context, *CheckSufficientBalanceRequest) (*CheckSufficientBalanceResponse, error)
	// 构建用于签名的未签名交易原始数据
	BuildSignRawData(context.Context, *BuildSignRawDataRequest) (*BuildSignRawDataResponse, error)
	// 广播已签名交易到网络
	TxBroadcast(context.Context, *TxBroadcastRequest) (*TxBroadcastResponse, error)
	// 查询余额
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	mustEmbedUnimplementedTxBuilderServer()
}

// UnimplementedTxBuilderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTxBuilderServer struct{}

func (UnimplementedTxBuilderServer) ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertAddress not implemented")
}
func (UnimplementedTxBuilderServer) VerifyAddress(context.Context, *VerifyAddressRequest) (*VerifyAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAddress not implemented")
}
func (UnimplementedTxBuilderServer) VerifyContractAddress(context.Context, *VerifyContractAddressRequest) (*VerifyContractAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyContractAddress not implemented")
}
func (UnimplementedTxBuilderServer) CheckSufficientBalance(context.Context, *CheckSufficientBalanceRequest) (*CheckSufficientBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSufficientBalance not implemented")
}
func (UnimplementedTxBuilderServer) BuildSignRawData(context.Context, *BuildSignRawDataRequest) (*BuildSignRawDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildSignRawData not implemented")
}
func (UnimplementedTxBuilderServer) TxBroadcast(context.Context, *TxBroadcastRequest) (*TxBroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TxBroadcast not implemented")
}
func (UnimplementedTxBuilderServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedTxBuilderServer) mustEmbedUnimplementedTxBuilderServer() {}
func (UnimplementedTxBuilderServer) testEmbeddedByValue()                   {}

// UnsafeTxBuilderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TxBuilderServer will
// result in compilation errors.
type UnsafeTxBuilderServer interface {
	mustEmbedUnimplementedTxBuilderServer()
}

func RegisterTxBuilderServer(s grpc.ServiceRegistrar, srv TxBuilderServer) {
	// If the following call panics, it indicates UnimplementedTxBuilderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TxBuilder_ServiceDesc, srv)
}

func _TxBuilder_ConvertAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).ConvertAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_ConvertAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).ConvertAddress(ctx, req.(*ConvertAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_VerifyAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).VerifyAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_VerifyAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).VerifyAddress(ctx, req.(*VerifyAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_VerifyContractAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyContractAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).VerifyContractAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_VerifyContractAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).VerifyContractAddress(ctx, req.(*VerifyContractAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_CheckSufficientBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSufficientBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).CheckSufficientBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_CheckSufficientBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).CheckSufficientBalance(ctx, req.(*CheckSufficientBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_BuildSignRawData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildSignRawDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).BuildSignRawData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_BuildSignRawData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).BuildSignRawData(ctx, req.(*BuildSignRawDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_TxBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).TxBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_TxBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).TxBroadcast(ctx, req.(*TxBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxBuilder_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxBuilderServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxBuilder_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxBuilderServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TxBuilder_ServiceDesc is the grpc.ServiceDesc for TxBuilder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TxBuilder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "txbuilder.TxBuilder",
	HandlerType: (*TxBuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertAddress",
			Handler:    _TxBuilder_ConvertAddress_Handler,
		},
		{
			MethodName: "VerifyAddress",
			Handler:    _TxBuilder_VerifyAddress_Handler,
		},
		{
			MethodName: "VerifyContractAddress",
			Handler:    _TxBuilder_VerifyContractAddress_Handler,
		},
		{
			MethodName: "CheckSufficientBalance",
			Handler:    _TxBuilder_CheckSufficientBalance_Handler,
		},
		{
			MethodName: "BuildSignRawData",
			Handler:    _TxBuilder_BuildSignRawData_Handler,
		},
		{
			MethodName: "TxBroadcast",
			Handler:    _TxBuilder_TxBroadcast_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _TxBuilder_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/txbuilder.proto",
}
